// Static data for RK Infrastructure, Architecture & Project Management Consultancy

export const landingBoxes = [
  {
    id: 'rk',
    title: 'RK',
    subtitle: 'RamKrishan Enterprises',
    description: 'Second generation consultancy firm delivering excellence',
    href: '/home',
    image: 'https://images.pexels.com/photos/3862132/pexels-photo-3862132.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    hoverText: 'Explore our firm',
  },
  {
    id: 'infrastructure',
    title: 'Infrastructure',
    subtitle: 'Civil & Industrial Works',
    description: 'Strategic infrastructure planning and engineering',
    href: '/infrastructure',
    image: 'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    hoverText: 'View Infrastructure Services',
  },
  {
    id: 'architecture',
    title: 'Architecture',
    subtitle: 'Design & Planning',
    description: 'Functional, aesthetic and sustainable designs',
    href: '/architecture',
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    hoverText: 'View Architecture Services',
  },
  {
    id: 'pmc',
    title: 'Project Management Consultancy',
    subtitle: 'PMC Services',
    description: 'End-to-end project coordination and delivery',
    href: '/pmc',
    image: 'https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    hoverText: 'View PMC Services',
  },
];

export const infrastructureProjects = [
  {
    id: 'residential-township',
    slug: 'residential-township',
    category: 'Residential',
    title: 'Residential Township Construction',
    location: 'Mumbai, Maharashtra',
    year: '2023',
    status: 'Completed',
    scope: 'Complete township planning, construction supervision, utilities coordination',
    image: 'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A comprehensive residential township project spanning over 15 acres in the outskirts of Mumbai. The project involved complete master planning, road network design, underground utility coordination, and construction supervision for 250+ residential units including row houses and holiday homes.',
    facts: [
      { label: 'Area', value: '15 Acres' },
      { label: 'Units', value: '250+' },
      { label: 'Duration', value: '24 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Construction World Magazine - June 2023', 'Maharashtra Infrastructure Report 2023'],
  },
  {
    id: 'industrial-warehouse',
    slug: 'industrial-warehouse',
    category: 'Industrial',
    title: 'Industrial Warehouse Complex',
    location: 'Pune, Maharashtra',
    year: '2022',
    status: 'Completed',
    scope: 'Factory and warehouse construction, structural design, site development',
    image: 'https://images.pexels.com/photos/236705/pexels-photo-236705.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/236705/pexels-photo-236705.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1797394/pexels-photo-1797394.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A large-scale industrial complex comprising multiple warehouse units and a central factory facility. The project demanded precision in structural engineering, fire safety compliance, heavy load floor design, and efficient logistics planning for movement of goods.',
    facts: [
      { label: 'Built-up Area', value: '80,000 sq ft' },
      { label: 'Warehouses', value: '6 Units' },
      { label: 'Duration', value: '18 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Warehousing India Today - Jan 2023'],
  },
  {
    id: 'road-drainage',
    slug: 'road-drainage',
    category: 'Civil',
    title: 'Road & Drainage Infrastructure',
    location: 'Thane, Maharashtra',
    year: '2023',
    status: 'Completed',
    scope: 'Road construction, drainage system design, civil works',
    image: 'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1117452/pexels-photo-1117452.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A critical urban infrastructure project involving the redesign and construction of 5km of internal roads within an industrial estate, complete with a modern stormwater drainage system. The project significantly improved connectivity and reduced waterlogging during monsoon season.',
    facts: [
      { label: 'Road Length', value: '5 km' },
      { label: 'Drainage Channels', value: '8 km' },
      { label: 'Duration', value: '12 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: [],
  },
  {
    id: 'hospital-structural',
    slug: 'hospital-structural',
    category: 'Structural Repair',
    title: 'Hospital Structural Repair & Waterproofing',
    location: 'Mumbai, Maharashtra',
    year: '2024',
    status: 'Completed',
    scope: 'Structural repairs, waterproofing, facade painting',
    image: 'https://images.pexels.com/photos/668300/pexels-photo-668300.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/668300/pexels-photo-668300.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1367269/pexels-photo-1367269.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Comprehensive structural rehabilitation of a 30-year-old hospital building. The project involved detailed structural assessment, concrete repair, post-tensioning works, complete waterproofing of the terrace and external walls, along with fresh facade painting to restore the building\'s appearance and structural integrity.',
    facts: [
      { label: 'Building Age', value: '30 Years' },
      { label: 'Floors', value: 'G + 6' },
      { label: 'Duration', value: '8 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: [],
  },
  {
    id: 'commercial-hotel',
    slug: 'commercial-hotel',
    category: 'Commercial',
    title: 'Boutique Hotel Construction',
    location: 'Nashik, Maharashtra',
    year: '2023',
    status: 'Completed',
    scope: 'Hotel construction, MEP coordination, interior coordination',
    image: 'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1838554/pexels-photo-1838554.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A 40-room boutique hotel project featuring modern amenities, spa facilities, and a rooftop restaurant. The project demanded careful coordination of civil, mechanical, electrical, and interior works to meet hospitality standards within a tight 16-month timeline.',
    facts: [
      { label: 'Rooms', value: '40' },
      { label: 'Built-up Area', value: '22,000 sq ft' },
      { label: 'Duration', value: '16 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Hospitality Design India - Dec 2023'],
  },
  {
    id: 'row-house',
    slug: 'row-house',
    category: 'Residential',
    title: 'Holiday Home Development',
    location: 'Alibag, Maharashtra',
    year: '2024',
    status: 'Ongoing',
    scope: 'Row house and holiday home construction',
    image: 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A premium holiday home project near the Alibag coast featuring 20 luxury row houses with private gardens. The project focuses on sustainable construction practices, rainwater harvesting, and green landscaping to create an eco-friendly retreat experience.',
    facts: [
      { label: 'Units', value: '20' },
      { label: 'Plot Size', value: '1200 sq ft each' },
      { label: 'Duration', value: '20 Months' },
      { label: 'Status', value: 'Ongoing' },
    ],
    publications: [],
  },
];

export const architectureProjects = [
  {
    id: 'corporate-office',
    slug: 'corporate-office',
    category: 'Commercial',
    title: 'Corporate Office Design',
    location: 'BKC, Mumbai',
    year: '2023',
    status: 'Completed',
    scope: 'Architectural design, 2D/3D planning, interior space planning',
    image: 'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1181316/pexels-photo-1181316.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A modern corporate office spread across three floors in the heart of BKC, Mumbai. The design prioritizes open collaboration zones, private meeting rooms, and ergonomic workspaces. Natural lighting strategies and sustainable materials were incorporated throughout.',
    facts: [
      { label: 'Area', value: '12,000 sq ft' },
      { label: 'Floors', value: '3' },
      { label: 'Capacity', value: '200 employees' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Interior Design India - 2023'],
  },
  {
    id: 'residential-villa',
    slug: 'residential-villa',
    category: 'Residential',
    title: 'Luxury Residential Villa',
    location: 'Lonavala, Maharashtra',
    year: '2024',
    status: 'Completed',
    scope: 'Complete architectural design, elevation design, 3D visualization',
    image: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A bespoke luxury villa nestled in the serene hills of Lonavala. The design integrates seamlessly with the natural landscape, featuring panoramic views, infinity pool, and sustainable architecture principles including passive cooling and rainwater harvesting.',
    facts: [
      { label: 'Plot Area', value: '5000 sq ft' },
      { label: 'Built-up Area', value: '3200 sq ft' },
      { label: 'Bedrooms', value: '4 BHK' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: [],
  },
  {
    id: 'school-design',
    slug: 'school-design',
    category: 'Institutional',
    title: 'Modern School Campus',
    location: 'Pune, Maharashtra',
    year: '2022',
    status: 'Completed',
    scope: 'Campus design, space planning, sustainable architecture',
    image: 'https://images.pexels.com/photos/2982449/pexels-photo-2982449.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/2982449/pexels-photo-2982449.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/207692/pexels-photo-207692.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/256490/pexels-photo-256490.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A forward-thinking K-12 school campus designed to foster creativity and learning. The campus features flexible classroom layouts, dedicated STEM labs, amphitheater, and extensive green spaces. Child-safe design principles and passive ventilation systems were prioritized throughout.',
    facts: [
      { label: 'Campus Area', value: '3 Acres' },
      { label: 'Classrooms', value: '40' },
      { label: 'Students', value: '1200' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Education Design India - 2022'],
  },
  {
    id: 'facade-renovation',
    slug: 'facade-renovation',
    category: 'Renovation',
    title: 'Commercial Complex Facade Renovation',
    location: 'Andheri, Mumbai',
    year: '2024',
    status: 'Completed',
    scope: 'Facade redesign, elevation design, renovation planning',
    image: 'https://images.pexels.com/photos/221502/pexels-photo-221502.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/221502/pexels-photo-221502.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/417273/pexels-photo-417273.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/162539/architecture-building-amsterdam-blue-sky-162539.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Complete facade transformation of a dated 1990s commercial complex. The project involved stripping the old cladding, redesigning the elevation with contemporary glass and aluminum composite panels, and integrating LED lighting to create a striking night-time presence.',
    facts: [
      { label: 'Facade Area', value: '15,000 sq ft' },
      { label: 'Floors', value: 'G + 8' },
      { label: 'Duration', value: '6 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: [],
  },
  {
    id: 'hospital-design',
    slug: 'hospital-design',
    category: 'Healthcare',
    title: 'Multi-Specialty Hospital Design',
    location: 'Navi Mumbai',
    year: '2023',
    status: 'Completed',
    scope: 'Hospital architecture, space planning, medical facility design',
    image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/668300/pexels-photo-668300.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/247786/pexels-photo-247786.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Architectural design for a 150-bed multi-specialty hospital focusing on patient-centric spaces, efficient workflow, and infection control compliance. The design incorporates natural lighting in patient wards, clear wayfinding systems, and separate zones for OPD, IPD, diagnostics, and emergency services.',
    facts: [
      { label: 'Beds', value: '150' },
      { label: 'Built-up Area', value: '65,000 sq ft' },
      { label: 'Floors', value: 'G + 5' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Healthcare Architecture India - 2023'],
  },
  {
    id: 'turnkey-apartment',
    slug: 'turnkey-apartment',
    category: 'Residential',
    title: 'Turnkey Apartment Project',
    location: 'Borivali, Mumbai',
    year: '2024',
    status: 'Ongoing',
    scope: 'Complete turnkey solution - design, approvals, execution',
    image: 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'A complete turnkey residential project involving 60 apartments across two towers. Our scope covers architectural design, obtaining all statutory approvals, detailed engineering drawings, construction supervision, and interior design coordination to deliver ready-to-occupy units.',
    facts: [
      { label: 'Apartments', value: '60' },
      { label: 'Towers', value: '2' },
      { label: 'Configuration', value: '1, 2 & 3 BHK' },
      { label: 'Status', value: 'Ongoing' },
    ],
    publications: [],
  },
];

export const pmcProjects = [
  {
    id: 'infrastructure-pmc',
    slug: 'infrastructure-pmc',
    category: 'Infrastructure PMC',
    title: 'Urban Road Infrastructure PMC',
    location: 'Thane Municipal Area',
    year: '2023',
    status: 'Completed',
    scope: 'Complete project management, contractor coordination, quality monitoring',
    image: 'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1118873/pexels-photo-1118873.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1563256/pexels-photo-1563256.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Provided end-to-end Project Management Consultancy for a 12km urban road widening and improvement project. Our team managed contractor tendering, site mobilization, quality checks, billing verification, and monthly progress reporting to the municipal authority.',
    facts: [
      { label: 'Road Length', value: '12 km' },
      { label: 'Project Value', value: '18 Cr' },
      { label: 'Duration', value: '14 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Urban Infrastructure Quarterly - 2023'],
  },
  {
    id: 'commercial-pmc',
    slug: 'commercial-pmc',
    category: 'Commercial PMC',
    title: 'IT Park Development PMC',
    location: 'Navi Mumbai',
    year: '2022',
    status: 'Completed',
    scope: 'Project planning, cost control, site supervision, progress reporting',
    image: 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/416405/pexels-photo-416405.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'PMC services for a Grade-A IT park development comprising 4 office towers. We established a robust project monitoring system, conducted weekly site reviews, managed 8 specialist contractors, and ensured strict compliance with safety regulations throughout construction.',
    facts: [
      { label: 'Towers', value: '4' },
      { label: 'Total Area', value: '4.5 Lakh sq ft' },
      { label: 'Project Value', value: '120 Cr' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['PMC Excellence Awards Shortlist 2022'],
  },
  {
    id: 'residential-pmc',
    slug: 'residential-pmc',
    category: 'Residential PMC',
    title: 'Affordable Housing PMC',
    location: 'Kalyan, Maharashtra',
    year: '2024',
    status: 'Ongoing',
    scope: 'Liaising, project scheduling, cost estimation, site supervision',
    image: 'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'Providing comprehensive PMC services for an MHADA affordable housing scheme with 500 residential units. Our services cover complete liaisoning with government authorities, RERA compliance, financial reporting, contractor management, and monthly progress tracking.',
    facts: [
      { label: 'Units', value: '500' },
      { label: 'Project Value', value: '75 Cr' },
      { label: 'Duration', value: '30 Months' },
      { label: 'Status', value: 'Ongoing' },
    ],
    publications: [],
  },
  {
    id: 'industrial-pmc',
    slug: 'industrial-pmc',
    category: 'Industrial PMC',
    title: 'Pharmaceutical Factory PMC',
    location: 'Tarapur, Maharashtra',
    year: '2023',
    status: 'Completed',
    scope: 'Complete PMC for GMP-compliant pharmaceutical manufacturing facility',
    image: 'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/236705/pexels-photo-236705.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1797394/pexels-photo-1797394.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    description: 'End-to-end project management for a GMP-compliant pharmaceutical factory. The project required strict adherence to FDA and WHO-GMP guidelines. Our team managed all civil, MEP, and validation works while maintaining rigorous documentation standards for regulatory submissions.',
    facts: [
      { label: 'Facility Area', value: '40,000 sq ft' },
      { label: 'Project Value', value: '30 Cr' },
      { label: 'Duration', value: '20 Months' },
      { label: 'Status', value: 'Completed' },
    ],
    publications: ['Pharma Manufacturing India - 2023'],
  },
];

export const teamMembers = [
  {
    name: 'Raju Balsalta',
    role: 'Principal Consultant & Founder',
    experience: '25+ Years',
    expertise: 'Infrastructure Planning & Project Management',
    image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    name: 'Bharat Upadyaya',
    role: 'Lead Architect',
    experience: '15+ Years',
    expertise: 'Architectural Design & 3D Visualization',
    image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    name: 'Hitendra',
    role: 'Senior Civil Engineer',
    experience: '18+ Years',
    expertise: 'Structural Design & Site Supervision',
    image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
  {
    name: 'Yadvendra Dichwalekar',
    role: 'PMC Manager',
    experience: '12+ Years',
    expertise: 'Project Scheduling & Cost Control',
    image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
  },
];

export const testimonials = [
  {
    name: 'Vikram Shah',
    company: 'Shah Developers',
    text: 'Professional planning and excellent project coordination throughout the project lifecycle. RK Enterprises delivered our township project on time and within budget.',
    rating: 5,
  },
  {
    name: 'Dr. Meena Joshi',
    company: 'Joshi Hospital Group',
    text: 'Highly reliable consultancy team with strong technical expertise. Their hospital design perfectly balanced functionality with a healing environment.',
    rating: 5,
  },
  {
    name: 'Ravi Mehta',
    company: 'Mehta Industries Ltd.',
    text: 'Delivered our warehouse project with exceptional quality and timely execution. Their site supervision team was always proactive in resolving challenges.',
    rating: 5,
  },
  {
    name: 'Priya Nair',
    company: 'Nair Educational Trust',
    text: 'Outstanding architectural design for our school campus. The team understood our vision and translated it into a functional, inspiring learning environment.',
    rating: 5,
  },
];

export const navLinks = [
  { label: 'RK', href: '/home' },
  { label: 'Infrastructure', href: '/infrastructure' },
  { label: 'Architecture', href: '/architecture' },
  { label: 'PMC', href: '/pmc' },
];
